services: 
  - docker

before_install:
  - docker build -t ankesh/docker-react  -f Dockerfile.dev .

script: 
  - echo "skipping tests"

before_deploy: "echo 'ready?'"

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-example-app"
  env: "DockerExampleApp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-024995093762"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

after_deploy: "echo 'done'"