language: generic

services: 
  - docker

before_install:
  - docker build -t ankesh/docker-react -f Dockerfile.dev .

before_deploy: "echo 'ready?'"

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-024995093762"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: 
    secure: "AKIAQLUOS3UBEZTBXIBP"
  secret_access_key: 
    secure: "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"

after_deploy: "echo 'done'"

script: 
  - docker run ankesh/docker-react npm run test -- --coverage