language: generic

services: 
  - docker

before_install:
  - docker build -t ankesh/docker-react -f Dockerfile.dev .

script: 
  - docker run ankesh/docker-react npm run test -- --coverage

before_deploy: "echo 'ready?'"

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-024995093762"
  bucket_path: "docker-react"
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"

after_deploy: "echo 'done'"